# renew_before_expiry = 30 days
version = 4.0.0
archive_dir = /etc/letsencrypt/archive/thedailydose.live
cert = /etc/letsencrypt/live/thedailydose.live/cert.pem
privkey = /etc/letsencrypt/live/thedailydose.live/privkey.pem
chain = /etc/letsencrypt/live/thedailydose.live/chain.pem
fullchain = /etc/letsencrypt/live/thedailydose.live/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = 31743186e55ff251ab117d7675f22889
pref_challs = dns-01,
authenticator = manual
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
